### DISCUSSION TITLE
rendition-menu doesn't work in Safari

### DISCUSSION THREAD

**Discussion by MarkLyck** [muxinc/media-chrome#1063] [Q&A]
When using rendition menu, the renditions work in Chrome:

<img width="168" alt="Image" src="https://github.com/user-attachments/assets/7ff27230-baed-4f2e-93ee-043cc6c56933" />

But in Safari they options are not visible:

<img width="232" alt="Image" src="https://github.com/user-attachments/assets/f61a3232-2f78-424a-8219-b3cc9d6dd407" />

I used the example from the docs:

```
<media-rendition-menu hidden anchor="auto">
        <div slot="header">Quality</div>
</media-rendition-menu>
```

```
<media-rendition-menu-button></media-rendition-menu-button>
```

**Comment by luwes** [comment]
this is probably because on Safari, native HLS is used and that information is not available.

nowadays you could either enable (managed) media source on hls.js which will work on desktop Safari and >= iOS 17.
then the renditions will become available if the videoRenditions are populated.

or you can hide the rendition menu button on devices that do not support it.

```css
    media-captions-button:not([mediasubtitleslist]),
    media-captions-menu:not([mediasubtitleslist]),
    media-captions-menu-button:not([mediasubtitleslist]),
    media-audio-track-menu[mediaaudiotrackunavailable],
    media-audio-track-menu-button[mediaaudiotrackunavailable],
    media-rendition-menu[mediarenditionunavailable],
    media-rendition-menu-button[mediarenditionunavailable],
    media-volume-range[mediavolumeunavailable],
    media-airplay-button[mediaairplayunavailable],
    media-fullscreen-button[mediafullscreenunavailable],
    media-cast-button[mediacastunavailable],
    media-pip-button[mediapipunavailable] {
      display: none;
    }
```
