### DISCUSSION TITLE
Add a CSS variable for --media-text-color

### DISCUSSION THREAD

**Discussion by dylanjha** [muxinc/media-chrome#198] [Proposals]
I was attempting to override the color of the controls with #f97316 in the "basic" example:

```css
<style>
  media-controller {
    --media-icon-color: #f97316;
    --media-range-bar-color: #f97316;
  }
</style>
```

<img width="763" alt="basic-orange_2022-04-06_15-08-04" src="https://user-images.githubusercontent.com/764988/162080379-0e82d8f6-c4f7-4b65-a422-397b53a10d7e.png">

^ Everything looks good, except I don't have a way to change the color of the text to match the icons

Seems like maybe there's a `--media-text-color` (better name?) missing? I couldn't find any appropriate [vars in the docs](https://github.com/muxinc/media-chrome/blob/main/docs/styling.md)
