### DISCUSSION TITLE
Shared data url based stylesheet

### DISCUSSION THREAD

**Discussion by luwes** [muxinc/media-chrome#708] [Proposals]
Wondering if we could make use of a shared data url stylesheet that could be shared across multiple components.

https://stackoverflow.com/questions/23807954/is-it-valid-to-use-datatext-css

Supposedly browsers efficiently use the same stylesheet across components.
https://developer.chrome.com/en/articles/declarative-shadow-dom/#server-rendering-with-style

> Inline and external stylesheets are fully supported inside Declarative Shadow Roots using the standard `<style>` and `<link>` tags:

```html
<nineties-button>
  <template shadowrootmode="open">
    <style>
      button {
        color: seagreen;
      }
    </style>
    <link rel="stylesheet" href="/comicsans.css" />
    <button>
      <slot></slot>
    </button>
  </template>
  I'm Blue
</nineties-button>
```

> Styles specified this way are also highly optimized: if the same stylesheet is present in multiple Declarative Shadow Roots, it is only loaded and parsed once. The browser uses a single backing CSSStyleSheet that is shared by all of the shadow roots, eliminating duplicate memory overhead.

---

it would be nice for large CSS blocks repeating across components like 

```css
:host {
    font: var(--media-font,
      var(--media-font-weight, normal)
      var(--media-font-size, 15px) /
      var(--media-text-content-height, var(--media-control-height, 24px))
      var(--media-font-family, helvetica neue, segoe ui, roboto, arial, sans-serif));
    color: var(--media-text-color, var(--media-primary-color, rgb(238 238 238)));
}
```
