### DISCUSSION TITLE
Media Chrome picks up CSS variables from my globals file

### DISCUSSION THREAD

**Discussion by ADTC** [muxinc/media-chrome#903] [General]
In my globals file, there are CSS variables defined in `:root` as follows:

```scss
:root {
  --border-radius: 8px !important;
  --primary: #aabbcc !important;
  // and others
}
```

These are getting picked up by Media Chrome and applied to the buttons. I can't find an effective way to avoid this.
