### ISSUE TITLE
Examples have layout issues in desktop safari fullscreen

### ISSUE THREAD

**Issue by heff** [muxinc/media-chrome#121]
In just the examples the controls seem to sit partially below the screen and the video doesn't fill the screen horizontally. This only happens in Safari desktop. It does not happen on the media-chrome.org homepage demo.

Haven't had a chance to dig into it, but it's worth understanding what's going on since it's our main examples.

### Repo examples fullscreen
![image](https://user-images.githubusercontent.com/166/150660019-7f40bc53-eb8f-49c3-b466-1cabceed35ee.png)

### Media-chrome.org fullscreen
![image](https://user-images.githubusercontent.com/166/150660056-0e8aee5f-0fe5-4770-88d6-32e542b98573.png)

**Comment by cjpillsbury** [comment]
@heff Yup haven't dug under the hood to see how to resolve this but it looks like when we're in fullscreen on Safari, stuff like padding/margins/etc are still applied from all ancestors of the fullscreen element (i.e. `<media-controller>` element). Seeing if I can do anything clever with `:-webkit-full-screen-ancestor:not(iframe)` (which is what Safari automatically adds to ancestors of the fullscreen element). 🤞

**Comment by cjpillsbury** [comment]
I have a working solution locally, but it required extending `:-webkit-full-screen-ancestor:not(iframe)` on the DOM (and not in e.g. the `<media-controller>` shadow DOM. We'll have to figure out tradeoffs here on implementation if we're avoiding requiring any CSS when using Media Chrome. fwiw I think this is actually an oversight in Safari's implementation, since they're clearly trying to handle this kind of stuff with their user agent stylesheet. Here's what's currently automatically added with their selector:

```css
:-webkit-full-screen-ancestor:not(iframe) {
z-index: auto;
position: static;
opacity: 1;
transform: none;
-webkit-mask-image: none;
-webkit-mask-source-type: initial;
-webkit-mask-position-x: initial;
-webkit-mask-position-y: initial;
-webkit-mask-size: initial;
-webkit-mask-repeat-x: initial;
-webkit-mask-repeat-y: initial;
-webkit-mask-origin: initial;
-webkit-mask-clip: initial;
filter: none;
transition-duration: initial;
transition-timing-function: initial;
transition-delay: initial;
transition-property: none;
-webkit-box-reflect: none;
perspective: none;
-webkit-transform-style: flat;
overflow-x: visible;
overflow-y: visible;
}
```
Here's what I added:
```css
:-webkit-full-screen-ancestor:not(iframe) {
  padding: 0;
  margin: 0;
  border: none;
}
```
note this is likely not exhaustive (box sizing for example, potential weirdness from different display settings, etc. etc.).
