### ISSUE TITLE
Disable control bar if native controls are visible 

### ISSUE THREAD

**Issue by evoactivity** [muxinc/media-chrome#693]
Keeping the right click menu seems to be desired behaviour for this library 
- https://github.com/muxinc/media-chrome/commit/a498bb15a5b9eebacc177e21e8206ffcbc717940
- https://github.com/muxinc/media-chrome/issues/299

So if a user enables the native controls it would be beneficial to turn off the control bar component.

I've tried using css to do this but the video/audio tag being in the shadow dom makes it impossible (as far as I know)

```css
media-controller [slot="media"]:has([controls]) ~ media-control-bar {
  display: none;
}
```

So I've created this [PR on custom-media-element](https://github.com/muxinc/custom-media-element/pull/4) which enables this css to work

```css
media-controller [slot="media"][controls] ~ media-control-bar {
  display: none;
}
```

I'm creating this issue to see if this css should be added to the default css of `<media-controller>`?
