### ISSUE TITLE
CC button default height isn't consistent with other buttons

### ISSUE THREAD

**Issue by heff** [muxinc/media-chrome#86]
Follow up on #74 

![image](https://user-images.githubusercontent.com/166/139509363-776d15bc-52ba-41ed-ac08-cb86cc19bf40.png)

https://media-chrome-err0093s8-mux.vercel.app/examples/standalone-controls.html

**Comment by cjpillsbury** [comment]
I think this should be part of an update to use "height" as a primary sizing dimension for buttons as opposed to "width". While there may be some edge cases, this should be resolved by simply updating `media-chrome-button` from:
```css
svg, img, ::slotted(svg), ::slotted(img) {
  width: var(--media-button-icon-width, 24px);
  height: var(--media-button-icon-height);
  /* ... */
}
```

to:
```css
svg, img, ::slotted(svg), ::slotted(img) {
  width: var(--media-button-icon-width);
  height: var(--media-button-icon-height, 24px);
  /* ... */
}
```

This should also resolve cases we've encountered in real-world use cases where custom icons required additional styles to avoid weird resizing when e.g. toggling between play and pause state.
