### ISSUE TITLE
Safari bug: Buttons in control bar don't fade out when moving away from playing video (not always)

### ISSUE THREAD

**Issue by ADTC** [muxinc/media-chrome#896]
This doesn't _always_ happen. It seems to be happening in my project, and also it happens at this link:

* https://www.media-chrome.org/docs/en/themes/responsive-themes

https://github.com/muxinc/media-chrome/assets/6047296/37abf8e9-0d06-48af-8353-24c5c9b4ef63

BUT it doesn't happen in this link:

* https://www.media-chrome.org/docs/en/get-started

In Chrome, it doesn't happen anywhere. (Recording for first link below.)

https://github.com/muxinc/media-chrome/assets/6047296/55657f92-e70e-492b-85fa-f0636a5ce453

**Comment by ADTC** [comment]
And, then after some time has passed, it starts to look like this. All the buttons disappear completely even in paused mode. Only the sliders are visible.

<img width="733" alt="image" src="https://github.com/muxinc/media-chrome/assets/6047296/b6667eeb-af92-48e4-931a-a62fd6126dbf">

**Comment by ADTC** [comment]
# I FIXED IT!

Apparently Safari really hates `opacity: 1`, so you have to use `opacity: 0.9999999` instead.

As a cautionary measure, I also put `opacity: 0.0000001` although it looked like `opacity: 0` works fine. You must have the second block though, otherwise the control bar will be stuck as visible all the time.

```scss
.controlBar {
  opacity: 0.9999999;
}

.video[userinactive]:not([mediapaused]):not([mediaisairplaying]):not([mediaiscasting]):not([audio])
  .controlBar {
  opacity: 0.0000001;
}
```

Where:
* `.video` is the `MediaController` or `media-controller`
* `.controlBar` is the `MediaControlBar` or `media-control-bar`
